const {
	src,
	dest
} = require('gulp');
const pug = require('gulp-pug');
const bs = require('browser-sync');
const htmlmin = require('gulp-htmlmin');

module.exports = function html() {
	return src(['src/**/*.pug', '!src/components/**/*.pug'])
		.pipe(pug())
		.pipe(htmlmin({
			includeAutoGeneratedTags: true,
  			removeAttributeQuotes: true,
  			removeComments: true,
  			removeRedundantAttributes: true,
  			removeScriptTypeAttributes: true,
  			removeStyleLinkTypeAttributes: true,
  			sortClassName: false,
  			useShortDoctype: true,
  			collapseWhitespace: true
		}))
		.pipe(dest('docs'))
		.pipe(bs.stream())
}