const {
	src,
	dest
} = require('gulp');
const include = require('gulp-file-include');
const bs = require('browser-sync');
const htmlmin = require('gulp-htmlmin');

module.exports = function html() {
	return src(['src/**/*.html', '!src/components/**/*.html'])
		.pipe(include())
		.pipe(htmlmin({
			includeAutoGeneratedTags: true,
  			removeAttributeQuotes: true,
  			removeComments: true,
  			removeRedundantAttributes: true,
  			removeScriptTypeAttributes: true,
  			removeStyleLinkTypeAttributes: true,
  			sortClassName: false,
  			useShortDoctype: true,
  			collapseWhitespace: true
		}))
		.pipe(dest('docs'))
		.pipe(bs.stream())
}